import Navbar from "@/components/modules/main-layout/nav-bar/Navbar";
import type { Metadata } from "next";
import { Space_Grotesk } from 'next/font/google';
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "@/components/modules/main-layout/query-provider";
import { Toaster } from "react-hot-toast";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased bg-black`}
      >
        <QueryProvider>

          <Navbar />
          {children}
          <Toaster />
        </QueryProvider>

      </body>
    </html>
  );
}
