import Navbar from "@/components/modules/main-layout/nav-bar/Navbar";
import QueryProvider from "@/components/modules/main-layout/query-provider";
import type { Metadata } from "next";
import { Space_Grotesk } from 'next/font/google';
import { Toaster } from "react-hot-toast";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Animal World",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>My Page Title</title>
        <link rel="icon" type="image/x-icon" href="/logo.png"/>
      </head>
      <body
        className={`${spaceGrotesk.className} antialiased bg-black`}
      >
        <QueryProvider>
          <Navbar />
          {children}
          <Toaster />
        </QueryProvider>

      </body>
    </html>
  );
}
